export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_NEWS_DETAILS = "FETCH_NEWS_DETAILS";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
// export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
// export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
