export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_NEWS_DETAILS = "FETCH_NEWS_DETAILS";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
